# Generated by Django 2.2.24 on 2021-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
